### PR TITLE
Finishing Python bindings for 1D drivers and adding Python tests

### PR DESCRIPTION
**Pull request by dfm**
I've cleaned things up a bit and finished the 1D bindings. I also added some tests to make sure that the Python bindings were doing sensible things. You can install [py.test](https://docs.pytest.org) and run the tests by executing `py.test -v` in the `python` directory after running `python setup.py build_ext --inplace`.

It shouldn't take much to add the 2D and 3D bindings but this is what I have for today!

Let me know if there are any issues.

### CODE REVIEW

**Comment by dfm** [comment]
One question: I changed the order of the inputs compared to C++ and set default values for `iflag` and `eps`. I'm happy to just require the user to input those if you think that that would be better.

**Comment by ahbarnett** [comment]
Hi Dan,
It looks great. However, I couldn't get it to run like I could demo.py (which still works).
What am I doing wrong?

alex@fiona /home/alex/numerics/finufft/python> python tests/test_1d.py 
Traceback (most recent call last):
  File "tests/test_1d.py", line 7, in <module>
    import finufft
ImportError: No module named finufft

It doesn't seem to matter what dir I call from.
The defaults look great. If I change the various flags I will add them to the defaults in the interface.cpp.
Looking forward to trying out... Best, Alex

**Comment by dfm** [comment]
Strange. What happens if you use:

```
python setup.py install
```

instead?

**Comment by ahbarnett** [comment]
It's a write permission issue - or maybe I don't know how to set up my python environment:

alex@fiona /home/alex/numerics/finufft/python> python setup.py install
running install
error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

    [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test-easy-install-13457.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python2.7/dist-packages/

...... ETC

However, I notice that the finufft makefile hasn't changed - should it also direct compilation and running of the test_1d.py ?
The stuff I put in the makefile was taken from your README:
# python wrapper... (awaiting completion)
python: python/setup.py python/demo.py python/finufft/build.py python/finufft/__
init__.py python/finufft/interface.cpp
	(cd python; rm -rf build ;\
	python setup.py build_ext --inplace ;\
	python demo.py )

Sorry I'm being a python noob here.

**Comment by dfm** [comment]
The permissions issues are because, despite the fact that everyone knows that it's a bad idea, the system-packaged Python installations require `su` permissions. Sorry to say but that's just always going to be an issue with your system and Python. If you actually want to use Python, I'd recommend switching to [Anaconda](https://www.continuum.io/downloads), otherwise, you can just `sudo python setup.py install`.

**Comment by dfm** [comment]
Actually, one other option would be to add the `finufft/python` directory to your `PYTHONPATH` environment variable and then just use the `build_ext --inplace` version still. Not a good general solution, but it'll probably do the trick here.

**Comment by ahbarnett** [comment]
Thanks!. Ok, the PYTHONPATH worked - so I guess we have to tell the user to do that before running the makefile? But I'm confused about making a makefile-driven self-test: my plan is that "make python" should make interfaces and run some kind of self-test or demo.

Now
python test_1d.py
exits silently but I don't think it's doing anything.

I also can do:

python
>>> import test_1d
>>> test_nufft1d1
<function test_nufft1d1 at 0x7fd0c106a230>
>>> test_nufft1d1()
>>> test_nufft1d2()
>>> test_nufft1d3()

Could your tester be auto-run from the top-level makefile, and print out the error figure, and "passed" if the assert on this error figure is ok?

I'm fading & am running a 2-day workshop in Yale starting Fri. I might be able to test a little more tomorrow. Cheers, Alex

**Comment by dfm** [comment]
As I said in the initial comment, the tests are meant to be run using one of the Python unit testing frameworks (I use [py.test](https://docs.pytest.org/)). If you have py.test installed, you run `py.test -v` in the `python` directory to execute the tests.

I don't think that packaging this using the Makefile is a good idea because everything is always much easier if you just use Python's packaging tools. In fact, it might be better to just break the Python bindings out into their own repository (I'm happy to manage that) and give a link from this one, because that might make distribution easier.

**Comment by dfm** [comment]
And no, we shouldn't tell people to set their `PYTHONPATH` … 😄 

Good night and enjoy the workshop!

**Comment by ahbarnett** [comment]
Hi Dan, I installed pytest and py.test -v worked perfectly. I agree that the makefile should call demo.py simliar to now (since it's important that "make python" run something to show the wrappers worked). Instructions can tell the user to install pytest and run the unit tests themselves.
I am happy to extend demo.py to include a couple of other cases.
For the 2d and 3d, please go ahead w/ the wrappers in the same style.   (The unit tests are less crucial from our users end, since they can just see how to call as in demo.py).
Thanks so much! Cheers, Alex

**Comment by ahbarnett** [comment]
Hi Dan, You'll notice I just changed the opts interface, killing maxnalloc and adding a FFTW control. Make sure you pull before generalizing yours to 2d & 3d. Or, tell me to do it and I'll give it a shot. Cheers, Alex

**Pull request merged**
